# Generated by Django 5.0.6 on 2026-08-15 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by_type', models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], max_length=20)),
                ('opportunity_type', models.CharField(choices=[('franchise', 'Franchise'), ('dealer', 'Dealer'), ('associate', 'Associate'), ('job', 'Job')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('investment_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('investment_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('number_required', models.PositiveIntegerField(default=1)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('experience_required', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['opportunity_type', 'posted_by_type', 'status'], name='requirement_opportu_fde98a_idx'), models.Index(fields=['location'], name='requirement_locatio_a4504e_idx'), models.Index(fields=['industry'], name='requirement_industr_f1d4d8_idx')],
            },
        ),
    ]
