# Generated by Django 5.0.6 on 2026-08-15 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('business_type', models.CharField(blank=True, max_length=150)),
                ('registration_number', models.CharField(blank=True, help_text='GST / company registration', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('preferred_location', models.CharField(blank=True, max_length=150)),
                ('investment_capacity_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('investment_capacity_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('industry_preference', models.CharField(blank=True, max_length=150)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
